[versions]
jline = "3.25.1"
junit = "5.14.1"
assertj = "3.27.6"
native-build-tools = "0.11.1"
picocli = "4.7.6"
nexus = "2.0.0"
oshi = "6.9.2"
gradle-tooling-api = "9.2.1"
compile-testing = "0.21.0"

[libraries]
jline = { module = "org.jline:jline", version.ref = "jline" }
picocli = { module = "info.picocli:picocli", version.ref = "picocli" }
picocli-codegen = { module = "info.picocli:picocli-codegen", version.ref = "picocli" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
graalvm-native = { module = "org.graalvm.buildtools:native-gradle-plugin", version.ref = "native-build-tools" }
nexus-publishing-plugin = { module = "io.github.gradle-nexus.publish-plugin:io.github.gradle-nexus.publish-plugin.gradle.plugin", version.ref = "nexus" }
oshi-core = { module = "com.github.oshi:oshi-core", version.ref = "oshi" }
gradle-tooling-api = { module = "org.gradle:gradle-tooling-api", version.ref = "gradle-tooling-api" }
compile-testing = { module = "com.google.testing.compile:compile-testing", version.ref = "compile-testing" }

[bundles]
testing = ["junit-jupiter", "junit-platform-launcher", "assertj-core"]
